FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy the Python script
COPY consumer.py /app/

# Install required dependencies
RUN pip install confluent-kafka

# Command to run the consumer
CMD ["python", "consumer.py"]
